### ISSUE TITLE
Under which license is this SDK shipped?

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#148]
### Is your feature request related to a problem? Please describe.

We have automatic license check for the dependency, apparently there is no information about the library licensing in the POM. I also didn't find any license information on the GitHub repository.

### Describe the solution you'd like.

Provide license information in the pom.
At least provide license information in the repo.

**Comment by scannillo** [comment]
👋 Hi @emartynov - thank you for opening this issue with the PayPal Android SDK. This a great callout. We definitely want to add a license, likely will be MIT or Apache.

I created a ticket for our team to tackle this (DTNOR-975 for tracking).

**Comment by emartynov** [comment]
Hi @scannillo, should I contact separately the cardinal SDK or you will ping them about the license also?

**Comment by scannillo** [comment]
👋 This has been resolved in PR #151 - thank you for raising this concern to us!

**Comment by emartynov** [comment]
@scannillo thank you for the update. What about the comment that touches situation with Cardinal SDK? It was not my choice to include that library in the project.

**Comment by emartynov** [comment]
@scannillo hi, what about paypal fraud protection SDK?

**Comment by emartynov** [comment]
@scannillo also other paypal libs:
* paypal partner auth
* auth sdk third party
* checkout sdk
