### ISSUE TITLE
Stuck on the web view

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#152]
### PayPal Android SDK Version

0.0.9

### Environment

Sandbox

### Android Version & Device

Any

### PayPal dependencies

paypal-payments-sdk = { module = "com.paypal.android:paypal-native-payments", version.ref = "paypal" }
paypal-core-payments-sdk = { module = "com.paypal.android:core-payments", version.ref = "paypal" }

### Describe the bug

Every time when I fire paypal checkout and enter email I see web view that says app id or return URL is wrong. No way I can proceed further.

iOS people are fine. Their SDK works (after they did some cache reset).

### To reproduce

1. Add paypal dependency
2. Configure according to documentation
3. Fire the order processin
4. Enter email

### Expected behavior

I can pay from my paypal balance.

**Comment by emartynov** [comment]
Exciting reply from PayPal support:
```
We usually advise our partners to integrate the checkout using JavaScript SDK (https://developer.paypal.com/docs/multiparty/checkout/). Would that be feasible on your end?
```
It looks like the only option I have now.

**Comment by sshropshire** [comment]
Hi @emartynov we appreciate the feedback and will look into this. This is for the native PayPal checkout correct? A screenshot would be most helpful here. I can forward it internally.

**Comment by emartynov** [comment]
Thank you for the reply, here is a screenshot 
![Screenshot_1687272415](https://github.com/paypal/Android-SDK/assets/295424/0158bc91-155c-403e-9b34-66fcaca0235c)

**Comment by sshropshire** [comment]
@emartynov thanks! Actually I misspoke, I meant to say a video if possible 🙏. Mostly trying to provide context to the team that maintains this library. Since the PayPal Native flow is highly visual, I have a feeling a video reproducing the issue may connect some dots on our end and lead to a faster fix.

**Comment by emartynov** [comment]
There is nothing extra in video - PayPal native login and start web page that lands on the screenshot.

**Comment by sshropshire** [comment]
@emartynov understood. Still, for the record a video will help us escalate the issue.

**Comment by emartynov** [comment]
Sure, here it is 


https://github.com/paypal/Android-SDK/assets/295424/32ce253a-6388-44a1-9445-d00660a76567

**Comment by emartynov** [comment]
@sshropshire this is resolved. Accidentally!

So, I've decided to try library update - the 0.0.10.
There was change - library requires client id instead of the token for the config.
However, I missed it and I was still passing the token instead. And bam - I was able to complete the flow.

**Comment by emartynov** [comment]
Closing this and I will open couple of new one

**Comment by tushe-tv** [comment]
@emartynov, I'm having trouble with the redirect_uri. I dont where to added it on the paypal dev console.
