### ISSUE TITLE
Additional template for filing bugs (like crashes)

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#163]
### Is your feature request related to a problem? Please describe.

Could you add an additional template for issues? Since it is tedious to fill some fields that need to be more relevant.

### Describe the solution you'd like.

Simple issue report template with just free text.

**Comment by scannillo** [comment]
👋 Hi - please use our [bug report](https://github.com/paypal/Android-SDK/issues/new/choose) template. We maintain several other open source SDKs and often have the free-form issue issues get abused and lack clear information.
