### ISSUE TITLE
Card payment

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#166]
### PayPal Android SDK Version

0.0.10

### Environment

Sandbox

### PayPal dependencies

paypal-card-payments-sdk = { module = "com.paypal.android:card-payments", version.ref = "paypal" }

### Describe the bug

I follow the documentation about how to make the card payment.
Whenever I start payment approval, I immediately get an error:
```
Error: 0 - Description: No value for message
```
BTW, no message field is mentioned in the code snippet in the documentation.

### To reproduce

1. Follow documentation
2. Start the card payment approval

### Expected behavior

No error or at least understandable error

**Comment by emartynov** [comment]
I passed the access token instead of the client id to the config. Maybe it is an issue. Whenever I started passing client id to the config I started to see other errors.

**Comment by emartynov** [comment]
Actually, no, this also doesn't work.

I follow the documentation for the card approval here https://github.com/paypal/Android-SDK/tree/main/docs/CardPayments
 
As for now, I can not make the card payments. Here is the info I got during the last testing.
 
Whenever I create the config with code that works for the native payment:
 
```
val coreConfig = CoreConfig(
    clientId = providerTokens!!.paymentAccessToken,
    environment = Environment.SANDBOX
)
``` 

I’m getting an error in the callback:

``` 
Error: 0 - Description: No value for message.
```

Whenever I create the config with code that API requires:
 
```
val coreConfig = CoreConfig(
    clientId = providerTokens!!.clientId,
    environment = Environment.SANDBOX
)
```
 
I’m getting an error in the callback:
 
```
Error: 404 - Description: The specified resource does not exist. -> [Issue: INVALID_RESOURCE_ID.
Error description: Specified resource ID does not exist. Please check the resource ID and try again.]
```

The correlation ID is `8dc297e4d9f8c`.
 
 
I don’t see anything in the log related to PayPal.

**Comment by sshropshire** [comment]
@emartynov circling back to this one. Does this still occur?

A 404 may be common when an order cannot be found that's associated with the `orderId` property passed in through `CardRequest`. It could also 404 if the order was created on the server side with a client id that's different from the one used when calling `CardClient#approveOrder()`.

**Comment by emartynov** [comment]
I think I can do the card payment just fine now.

**Comment by emartynov** [comment]
Ah, I remember the casue/fix - the card order can not be authorised and should always be collected.
