### ISSUE TITLE
Report bug in official Android app

### ISSUE THREAD

**Issue by Regenhardt** [paypal/paypal-android#187]
Where do I report a bug in the Android app? It prevents users of GBoard keyboard to enter amounts that contain decimal numbers when sending money, like 7.85€ or similar.

**Comment by saperi22** [comment]
@Regenhardt when you say official Android app, do you mean the PayPal Android application?
https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile

If you can describe the issue in detail, provide Android app version, device used and any other non-sensitive information you can provide, I can take it up to the consumer team that owns this application.

Apologies for directing you here without understanding the issue.

**Comment by scannillo** [comment]
Please see the instructions on [this forum post](https://www.paypal-community.com/t5/Products-and-Services-Archives/I-want-to-open-a-bug-report-on-the-paypal-app/td-p/1860458) for reporting bugs in the PayPal application.

This GitHub issues is for the PayPal Android SDK.
