### ISSUE TITLE
Error on /connect (set redirect_uri on developer dashboard)

### ISSUE THREAD

**Issue by tushe-tv** [paypal/paypal-android#200]
### PayPal Android SDK Version

1.0.0

### Environment

Sandbox

### PayPal dependencies

implementation "com.paypal.android:paypal-native-payments:1.0.0"

### Describe the bug

I'm getting an error when redirected to paypal connect. Where can I set the redirect_uri?

### To reproduce

https://www.sandbox.paypal.com/connect/?redirect_uri=com.paypalnativeexample%3A%2F%2Fpaypalpay&client_id=AT9gjC-cJyHQ1OkH-Iq93QOmdS4Rw34XsE0FBi4Su2YyVyS1TasFkGAsx_tXn3L3f55flvIgbLJR3d-4&response_type=code&state=08K1XY5uQ4e6TSpLZyAO_Q&scope=https%3A%2F%2Furi.paypal.com%2Fweb%2Fexperience%2Fincontextxo&code_challenge=MEUCIHD-54oEUKv4Z68vzhDaBWQaSmbTWI2Zu7YLQi9RjLX-AiEAuAuuRwwDFYIxWuWMZDUepOtfsGiS4wPoaoxYTVrlPnc&code_challenge_method=ES256&metadata_id=52T05402N01302820

### Expected behavior

Open login page

**Comment by sshropshire** [comment]
Hi @tushe-tv thanks for this feedback. Have you tried setting the `returnUrl` property when creating the `PayPalNativeCheckoutClient` ([example here](https://github.com/paypal/paypal-android/tree/main/docs/PayPalNativePayments#3-initiate-paypal-native-checkout))?

**Comment by tushe-tv** [comment]
Yes, but I could not found where, on paypal developer dashboard, to add the return url. 

I just found it:
When you enter to https://developer.paypal.com/ click on **App & Credentials** -> **REST API apps** section (select the app (or one of the apps, if more then one)) -> Scroll to **Features** and check **Log in with PayPal** (In **Advanced settings**  the return url can be add)

![paypal](https://github.com/paypal/paypal-android/assets/115789096/dcf5df66-b74f-45cc-84bb-bb78ee46f03d)

**Comment by sshropshire** [comment]
@tushe-tv Got it. Thanks for opening this GitHub issue! We'll take note of this feedback going forward.
