### ISSUE TITLE
Cant enter a decimal number

### ISSUE THREAD

**Issue by FreyLuis** [paypal/paypal-android#221]
### PayPal Android SDK Version

8.53.1

### Environment

Both

### PayPal dependencies

idk

### Describe the bug

The new textfield for the amount I want to send or request no longer allows me to enter a decimal number in germany. 

The reason for that is, that we use a comma instead of period for the decimal separator. The Problem is, that a comma isn't an option on the standard gboard numbers only keyboard. 

This wasn't a problem previously, since it added the decimal separator automatically (which also felt more intuitive imo).

### To reproduce

1. Change the language culture to something that uses a ',' as a decimal seperator
2. use gboard as the keyboard
3. try enter a decimal number

### Expected behavior

Allows me to enter a decimal number

**Comment by sshropshire** [comment]
Hi @FreyLuis we don't maintain any of the UI elements in our SDK at the moment, with the exception of the Payment Buttons. An you provide a screenshot of which UI element you're referring to?

**Comment by FreyLuis** [comment]
sorry, I confused this repo for the repo of the actual paypal app
