### ISSUE TITLE
Failed to build my project because of cardinalmobilesdk dependency

### ISSUE THREAD

**Issue by laurentvoodoo** [paypal/paypal-android#249]
### PayPal Android SDK Version

1.0.0

### Environment

Both

### PayPal dependencies

    implementation("com.paypal.android:paypal-native-payments:1.0.0")
    implementation("com.paypal.android:payment-buttons:1.0.0")

### Describe the bug

Since today, cannot build my project because `cardinalmobilesdk` dependency of paypal SDK is not resolved.
Maybe credentials to access https://cardinalcommerceprod.jfrog.io are deactivated on cardinal jfrog repository. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom
       - https://repo.maven.apache.org/maven2/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom
       - https://jitpack.io/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom
     Required by:
         project :app > project :feature:feature-deposit > com.paypal.android:paypal-native-payments:1.0.0 > com.paypal.checkout:android-sdk:1.1.0
```

### To reproduce

Add Paypal dependencies on project without gradle cache and build.

### Expected behavior

dependency is available

**Comment by laurentvoodoo** [comment]
same issue https://github.com/paypal/paypal-android/issues/250

**Comment by sarahkoop** [comment]
We have determined this is an issue with the availability of Cardinal's SDK version `2.2.7-2`, and we are working with the Cardinal team to get it resolved as soon as possible. We understand that this is blocking builds and CI so we are urgently working to resolve and we appreciate your patience! We will post any additional updates here.

**Comment by sarahkoop** [comment]
This issue was resolved by JFrog and Cardinal - builds and CI should be working again! Closing this issue, but please re-open if you continue to experience it
