### ISSUE TITLE
Unable to get cardinalmobilesdk because of 403 error

### ISSUE THREAD

**Issue by prof18** [paypal/paypal-android#272]
### PayPal Android SDK Version

1.4.1

### Environment

Both

### PayPal dependencies

```
implementation("com.paypal.android:paypal-native-payments:1.4.1")
```

### Describe the bug

From this morning, CI started failing because the `cardinalmobilesdk` lib could not be found. 

```
> Could not resolve all files for configuration ':app:productionReleaseRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5.
     Required by:
         project :app > com.paypal.android:paypal-native-payments:1.4.1 > com.paypal.checkout:android-sdk:1.3.2
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5.
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom'. Received status code 403 from server:
```

I've tried login in manually to `https://cardinalcommerceprod.jfrog.io/artifactory/android` with the shared credentials but no luck (error: `This request is blocked due to recurrent login failures, please try again in 17 seconds`.)

Is this issue maybe correlated to the sunsetting of JCenter? 🤔 

### To reproduce

Add the dependency without gradle cache 

### Expected behavior

The dependency can be downloaded

**Comment by sshropshire** [comment]
Hey @prof18 we were told the shared credentials would be valid through the end of the year, though I wouldn't be surprised if they stop working before then. Would you mind giving [these credentials](https://github.com/braintree/braintree_android/blob/main/v4.9.0%2B_MIGRATION_GUIDE.md#3d-secure) a try from our Braintree repo?

**Comment by prof18** [comment]
Sorry for the delay. Yeah, the credentials that you shared are working!
Lately, also the "original" ones are working again. 🤔 Maybe it was a temporary issue?

**Comment by sshropshire** [comment]
@prof18 most likely yes. We have gotten word that their JFrog instance is changing its authentication policy, but we've followed their guidance and re-generated the shared credentials.

Since this is working now I'll close, but feel free to re-open if you see any new auth issues. We do have the ability to re-issue those credentials when needed.
