### ISSUE TITLE
PaymentButtonContainer is not inflating in Android (0.8.1)

### ISSUE THREAD

**Issue by HafizAwaiskhan** [paypal/paypal-android#91]
**Description of bug:**
Using com.paypal.checkout.paymentbutton.PaymentButtonContainer with ('com.paypal.checkout:android-sdk:0.8.1') but its not rendering , inflating error in android.
How I can use that ? or there is some other approach ?

**Error**
D/nxoPayPalButton: eligibility status updated: Loading
D/nxoPayPalCreditButton: eligibility status updated: Loading
D/nxoPayLaterButton: eligibility status updated: Loading

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.cybermart.paypalcheckoutintegration/com.cybermart.paypalcheckoutintegration.MainActivity}: android.view.InflateException: Binary XML file line https://github.com/paypal/android-checkout-sdk/issues/10 in com.cybermart.paypalcheckoutintegration:layout/activity_main: Binary XML file line https://github.com/paypal/android-checkout-sdk/issues/10 in com.cybermart.paypalcheckoutintegration:layout/activity_main: Error inflating class com.paypal.checkout.paymentbutton.PaymentButtonContainer

**To Reproduce**
add 'com.paypal.checkout:android-sdk:0.8.1'
then add <com.paypal.checkout.paymentbutton.PaymentButtonContainer
android:id="@+id/payment_button_container"
android:layout_width="match_parent"
android:layout_height="wrap_content"
app:paypal_button_color="silver"
app:paypal_button_label="pay"
app:paypal_button_shape="rectangle"
app:paypal_button_size="large"
app:paypal_button_enabled="true">

**Comment by jcnoriega** [comment]
@HafizAwaiskhan Hi! This is not the team and repository that handles com.paypal.checkout:android-sdk, the correct repository is here: https://github.com/paypal/android-checkout-sdk. 
I can give you a quick tip though, i think you are not supposed to use the PaymentButtonContainer on your xml, i think you should use directly PayLaterButton, PayPalCreditButton or PayPalButton.
But please post your question on the provided link! Closing this issue
